### ISSUE TITLE
Update how to Cite Monarch on UI?

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#557] opened 2024-01-23 22:56 UTC
Under the section of the new UI for citing Monarch in publications, are the two publications listed still accurate? 
https://monarchinitiative.org/cite#in-publications

I am guessing we need to add the new NAR paper at a minimum. 

@mellybelly @cmungall @monicacecilia Do you have any thoughts on this?

**Comment by glass-ships** [comment] 2024-02-16 17:23
Potentially duplicate of #589

**Closed as completed** 2024-02-23 20:38 UTC
