### ISSUE TITLE
Add SAB Page to the Website

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#206] opened 2023-07-12 22:13 UTC
I suggest we add a page on the Website dedicated to the Monarch SAB. 

**Include:** 
- [ ] Members (picture, organization, position)
- [ ] Meeting Cadence
- [ ] SAB purpose

**Comment by sagehrke** [comment] 2023-07-12 22:13
@monicacecilia @putmantime Does this seem like a good idea? Or unnecessary?

**Comment by monicacecilia** [comment] 2023-07-14 17:11
dupe of #74

**Closed as completed by monicacecilia** 2023-07-14 17:11 UTC
Labels: duplicate
