### ISSUE TITLE
Clicking histopheno graph could filter annotation table

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#263] opened 2023-08-09 17:30 UTC
We might want to implement this a different way, but here's my context:

glaucoma was mentioned in the context of term labels that are the same between HP & MONDO, so I was looking at the MONDO glaucoma page. I thought it was interesting that there's a skeletal phenotype. 

<img width="874" alt="Screenshot 2023-08-09 at 10 25 39 AM" src="https://github.com/monarch-initiative/monarch-app/assets/4535019/45506f01-c406-47de-a058-b088797e061f">

I noticed that hovering over the bar changes the color, and it feels as if clicking on skeletal system might give me details. It's a jump between sections, but we certainly could apply a skeletal system filter to the annotations table.  (well, technically, we can't yet, so I'll make another issue for that)

**Comment by sagehrke** [comment] 2023-09-25 17:27
Related to issue #264

**Comment by monicacecilia** [comment] 2024-02-28 23:11
dupe of #440

**Closed as completed by monicacecilia** 2024-02-28 23:11 UTC
