### ISSUE TITLE
Information access is cumbersome

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#394] opened 2023-10-12 16:38 UTC
https://docs.google.com/document/d/1qdgn-FPNQbF1eRz2LnQIKzdcpRfhllRXo6eUdI8hPjY/edit#bookmark=id.grf18ku91e9t

Although the new interface is cleaner and fairly intuitive, it is quite cumbersome to access key information. If you want to see all phenotypes associated with a specific gene, this takes:
1) Scroll down through 4-page sections
2) Collect the correct type (and for disease or orthologs you need to know that  they are  hidden under this menu)
3) Click on the table
4) Select a per-page value greater than the total, so that you do not  need to scroll through
(This is also necessary because the summary does not appear to have any significance such as over-represented features).
It would be much better if “Quicklinks” to these details were provided via the “association counts” in the overview for impatient people.
Were follow-up interviews with the original testers to see if usability had been improved?

**Comment by amc-corey-cox** [comment] 2023-10-12 16:41
Vincent:
We can put "Associations" right under "Overview" probably.

I disagree that they are "hidden" under a menu. It's at the top of the section and the only interactable element. The only alternative I could see is listing them out in another tab group (above the "summary/table" tab group), but then you have to figure out what to do when there are 20 categories. Just show the top 3 by # of associations and hide the rest under a "show more..."? Show handpicked categories of note, e.g. disease/gene/pheno? I would expect different people to complain that it is hard to find their category of interest if we do this.

This is not a me question, I guess, but it sounds like they're saying the summary section is useless. Maybe we need to provide more useful summary data here.

Quicklinks: This is already implemented and live in next. Not sure if this person is looking at the right version of the site.

**Comment by amc-corey-cox** [comment] 2023-10-12 16:42
Nothing left for this except to respond

**Comment by vincerubinetti** [comment] 2023-10-12 17:07
Duplicate of #378. Please check this issue before creating new ones, I captured all of the ones I thought were in my purview in that issue.

**Closed as not planned by vincerubinetti** 2023-10-12 17:07 UTC
