### ISSUE TITLE
Entity-based search

### ISSUE THREAD

**Issue by sagehrke** [monarch-initiative/monarch-app#456] opened 2023-10-31 21:05 UTC
As discussed in the Technical call on Oct 31, 2023: 
> We want an entity-based search to emulate the behavior shown by 'search' in the Alliance website.

@kevinschaper and @putmantime please link any other search based tickets to this one so all our discussions can be referenced in one place.

**Comment by vincerubinetti** [comment] 2023-11-02 15:45
Duplicate of #451

**Closed as completed** 2023-11-02 22:04 UTC
