### ISSUE TITLE
Have taxon IDs instead of species as the name qualifier

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#389] opened 2023-10-12 15:52 UTC
Is there any reason to have taxon IDs instead of species as the name qualifier here? Not many people know taxon IDs.

Vikncent Rubinetti - I believe I have this info from the API. Should be easy to swap in the label instead of the id.

**Comment by vincerubinetti** [comment] 2023-10-12 15:53
dupe of #378

**Closed as not planned** 2023-10-12 16:06 UTC
