### ISSUE TITLE
Update Overview Page

### ISSUE THREAD

**Issue by monicacecilia** [monarch-initiative/monarch-app#437] opened 2023-10-24 20:42 UTC
The information on the [Overview page](https://monarchinitiative.org/overview) has aged and is outdated. 
Need to include: 
- updated figure outlining infrastructure
- updated text describing how it works (can come from the NAR paper)
- updated links to pertinent repos (kg building, ingest, etc.)

**Comment by sagehrke** [comment] 2023-10-24 21:02
duplicate of #436

**Closed as not planned by sagehrke** 2023-10-24 21:02 UTC
