### ISSUE TITLE
Affordance that shows that the analysis is running shows isn't always visible

### ISSUE THREAD

**Issue by kevinschaper** [monarch-initiative/monarch-app#391] opened 2023-10-12 16:05 UTC
When using the phenotype explorer and I clicked on the analyze button there as no indication that anything is happening so I clicked a few times until I realized that the analysis was running just outside of my view win my screen. Might be nice to engineer something that would give the user an indication that the analysis is running or to auto-scroll down to the analysis section.

**Comment by vincerubinetti** [comment] 2023-10-12 17:07
Duplicate of #378. Please check this issue before creating new ones, I captured all of the ones I thought were in my purview in that issue.

**Closed as not planned by vincerubinetti** 2023-10-12 17:07 UTC
