### ISSUE TITLE
Formatting of Headings broken with new Tables

### ISSUE THREAD

**Issue by amc-corey-cox** [monarch-initiative/monarch-app#848] opened 2024-10-11 18:08 UTC
In #775 - we somehow broke the formatting of the headers. I've undeleted the branch [issue-734-all-association-sections](https://github.com/monarch-initiative/monarch-app/tree/issue-734-all-association-sections) and added a comment to the PR.

I'm looking into the specific line that causes the problem.

**Comment by amc-corey-cox** [comment] 2024-10-11 18:24
The commit where the issue appears to have occurred is: c1dca62f

**Comment by ptgolden** [comment] 2024-10-11 18:34
The issue is that `text-align` is being set twice for heading elements that are children of AppSection components. Once in the global CSS settings:

https://github.com/monarch-initiative/monarch-app/blob/2c878e844bc2d10664d798570560c04fad6acc27/frontend/src/global/styles.scss#L33-L61

And then again in the AppSection container:

https://github.com/monarch-initiative/monarch-app/blob/2c878e844bc2d10664d798570560c04fad6acc27/frontend/src/components/AppSection.vue#L42-L51

Because the former's specificity is higher, it is being used. The solution is to take `text-align` out of the heading elements in the global CSS, because they are not always left aligned.

**Comment by ptgolden** [comment] 2024-10-11 18:38
The place where those changes were made is https://github.com/monarch-initiative/monarch-app/commit/2c878e844bc2d10664d798570560c04fad6acc27

**Comment by ptgolden** [comment] 2024-10-11 19:06
Ooops, specifically 4ae405bfe6c4c59f659093d6da8cd605466b31d0. In any case, if headings can be aligned multiple ways, then they their alignment probably shouldn't be defined globally.

**Comment by ptgolden** [comment] 2024-10-11 19:12
Fixed in https://github.com/monarch-initiative/monarch-app/commit/fe08db574ae204e36c03d563af8d4dc8fb978a0c

**Comment by ptgolden** [comment] 2024-10-11 19:14
> In https://github.com/monarch-initiative/monarch-app/pull/775 - we somehow broke the formatting of the headers. I've undeleted the branch [issue-734-all-association-sections](https://github.com/monarch-initiative/monarch-app/tree/issue-734-all-association-sections) and added a comment to the PR.

Since the PR is merged, it's not possible to add commits to it anymore on the `issue-734-all-associations-sections` branch. Happy to make a new PR.

**Comment by amc-corey-cox** [comment] 2024-10-11 19:22
I think we should make a new PR. - You may want to start from main or merge in main in order to make the PR a little more sane.

**Comment by amc-corey-cox** [comment] 2024-10-11 19:26
Oh, it looks like you may have already started from main. When you make the PR, I recommend you add Kevin as the reviewer just so he can see what was going on.

**Closed as completed** 2024-10-22 16:28 UTC
